// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafariWheels.API.Data;

#nullable disable

namespace SafariWheels.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012234712_SeedDataFixed")]
    partial class SeedDataFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafariWheels.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CarType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AverageRating = 4.8m,
                            CarType = "Sports Car",
                            Description = "Ultimate grand tourer with blistering performance.",
                            Engine = "V8 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "BMW",
                            Mileage = 5000,
                            Model = "M8 Competition",
                            PricePerDay = 2500m,
                            PricePerHour = 200m,
                            PricePerWeek = 15000m,
                            Province = "Gauteng",
                            Year = 2023
                        },
                        new
                        {
                            Id = -2,
                            AverageRating = 4.9m,
                            CarType = "Luxury",
                            Description = "Exquisite comfort and advanced tech for executives.",
                            Engine = "V6 Hybrid",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Mileage = 2000,
                            Model = "S-Class",
                            PricePerDay = 1800m,
                            PricePerHour = 150m,
                            PricePerWeek = 11000m,
                            Province = "Western Cape",
                            Year = 2024
                        },
                        new
                        {
                            Id = -3,
                            AverageRating = 4.7m,
                            CarType = "Sports Car",
                            Description = "Iconic supercar with unmatched handling.",
                            Engine = "Flat-6 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = false,
                            Make = "Porsche",
                            Mileage = 8000,
                            Model = "911 Turbo S",
                            PricePerDay = 3500m,
                            PricePerHour = 300m,
                            PricePerWeek = 20000m,
                            Province = "KwaZulu-Natal",
                            Year = 2023
                        },
                        new
                        {
                            Id = -4,
                            AverageRating = 4.6m,
                            CarType = "Sports Car",
                            Description = "Mid-engine thrill with Quattro grip.",
                            Engine = "V10",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Audi",
                            Mileage = 12000,
                            Model = "R8 V10",
                            PricePerDay = 2200m,
                            PricePerHour = 180m,
                            PricePerWeek = 13000m,
                            Province = "Gauteng",
                            Year = 2022
                        },
                        new
                        {
                            Id = -5,
                            AverageRating = 4.8m,
                            CarType = "SUV",
                            Description = "Ultimate luxury SUV for off-road elegance.",
                            Engine = "V8 Supercharged",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Range Rover",
                            Mileage = 1000,
                            Model = "SVAutobiography",
                            PricePerDay = 2000m,
                            PricePerHour = 160m,
                            PricePerWeek = 12000m,
                            Province = "Eastern Cape",
                            Year = 2024
                        },
                        new
                        {
                            Id = -6,
                            AverageRating = 4.9m,
                            CarType = "Coupe",
                            Description = "Italian grand tourer with passionate design.",
                            Engine = "V8 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Ferrari",
                            Mileage = 3000,
                            Model = "Roma",
                            PricePerDay = 4000m,
                            PricePerHour = 350m,
                            PricePerWeek = 24000m,
                            Province = "Mpumalanga",
                            Year = 2023
                        },
                        new
                        {
                            Id = -7,
                            AverageRating = 4.7m,
                            CarType = "Sports Car",
                            Description = "Exotic supercar with aggressive styling.",
                            Engine = "V10",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Mileage = 15000,
                            Model = "Huracan",
                            PricePerDay = 3800m,
                            PricePerHour = 320m,
                            PricePerWeek = 22000m,
                            Province = "Free State",
                            Year = 2022
                        },
                        new
                        {
                            Id = -8,
                            AverageRating = 4.5m,
                            CarType = "Sedan",
                            Description = "Electric hypercar with insane acceleration.",
                            Engine = "Electric Tri-Motor",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Tesla",
                            Mileage = 4000,
                            Model = "Model S Plaid",
                            PricePerDay = 1600m,
                            PricePerHour = 130m,
                            PricePerWeek = 9500m,
                            Province = "North West",
                            Year = 2024
                        },
                        new
                        {
                            Id = -9,
                            AverageRating = 4.8m,
                            CarType = "Convertible",
                            Description = "Opulent grand tourer for open-top luxury.",
                            Engine = "W12",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Bentley",
                            Mileage = 6000,
                            Model = "Continental GT",
                            PricePerDay = 2800m,
                            PricePerHour = 220m,
                            PricePerWeek = 17000m,
                            Province = "Northern Cape",
                            Year = 2023
                        },
                        new
                        {
                            Id = -10,
                            AverageRating = 5.0m,
                            CarType = "Luxury",
                            Description = "Bespoke serenity on wheels.",
                            Engine = "V12 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Rolls-Royce",
                            Mileage = 500,
                            Model = "Ghost",
                            PricePerDay = 5000m,
                            PricePerHour = 400m,
                            PricePerWeek = 30000m,
                            Province = "Limpopo",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("DropoffLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SafariWheels.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Address = "123 Luxury Avenue, Sandton",
                            DriverLicenseNumber = "ADMIN123",
                            Email = "admin@safariwheels.co.za",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "YWRtaW4xMjNzYWx0",
                            PhoneNumber = "+27 11 123 4567",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.Rental", b =>
                {
                    b.HasOne("SafariWheels.API.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafariWheels.API.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafariWheels.API.Models.Car", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SafariWheels.API.Models.User", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
