// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafariWheels.API.Data;

#nullable disable

namespace SafariWheels.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222141052_AddMessagesContactInfoLocations")]
    partial class AddMessagesContactInfoLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafariWheels.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("CarType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerWeek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AverageRating = 4.8m,
                            CarType = "Sports Car",
                            Description = "Ultimate grand tourer with blistering performance.",
                            Engine = "V8 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "BMW",
                            Mileage = 5000,
                            Model = "M8 Competition",
                            PricePerDay = 2500m,
                            PricePerHour = 200m,
                            PricePerWeek = 15000m,
                            Province = "Gauteng",
                            Year = 2023
                        },
                        new
                        {
                            Id = -2,
                            AverageRating = 4.9m,
                            CarType = "Luxury",
                            Description = "Exquisite comfort and advanced tech for executives.",
                            Engine = "V6 Hybrid",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Mileage = 2000,
                            Model = "S-Class",
                            PricePerDay = 1800m,
                            PricePerHour = 150m,
                            PricePerWeek = 11000m,
                            Province = "Western Cape",
                            Year = 2024
                        },
                        new
                        {
                            Id = -3,
                            AverageRating = 4.7m,
                            CarType = "Sports Car",
                            Description = "Iconic supercar with unmatched handling.",
                            Engine = "Flat-6 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = false,
                            Make = "Porsche",
                            Mileage = 8000,
                            Model = "911 Turbo S",
                            PricePerDay = 3500m,
                            PricePerHour = 300m,
                            PricePerWeek = 20000m,
                            Province = "KwaZulu-Natal",
                            Year = 2023
                        },
                        new
                        {
                            Id = -4,
                            AverageRating = 4.6m,
                            CarType = "Sports Car",
                            Description = "Mid-engine thrill with Quattro grip.",
                            Engine = "V10",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Audi",
                            Mileage = 12000,
                            Model = "R8 V10",
                            PricePerDay = 2200m,
                            PricePerHour = 180m,
                            PricePerWeek = 13000m,
                            Province = "Gauteng",
                            Year = 2022
                        },
                        new
                        {
                            Id = -5,
                            AverageRating = 4.8m,
                            CarType = "SUV",
                            Description = "Ultimate luxury SUV for off-road elegance.",
                            Engine = "V8 Supercharged",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Range Rover",
                            Mileage = 1000,
                            Model = "SVAutobiography",
                            PricePerDay = 2000m,
                            PricePerHour = 160m,
                            PricePerWeek = 12000m,
                            Province = "Eastern Cape",
                            Year = 2024
                        },
                        new
                        {
                            Id = -6,
                            AverageRating = 4.9m,
                            CarType = "Coupe",
                            Description = "Italian grand tourer with passionate design.",
                            Engine = "V8 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Ferrari",
                            Mileage = 3000,
                            Model = "Roma",
                            PricePerDay = 4000m,
                            PricePerHour = 350m,
                            PricePerWeek = 24000m,
                            Province = "Mpumalanga",
                            Year = 2023
                        },
                        new
                        {
                            Id = -7,
                            AverageRating = 4.7m,
                            CarType = "Sports Car",
                            Description = "Exotic supercar with aggressive styling.",
                            Engine = "V10",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Lamborghini",
                            Mileage = 15000,
                            Model = "Huracan",
                            PricePerDay = 3800m,
                            PricePerHour = 320m,
                            PricePerWeek = 22000m,
                            Province = "Free State",
                            Year = 2022
                        },
                        new
                        {
                            Id = -8,
                            AverageRating = 4.5m,
                            CarType = "Sedan",
                            Description = "Electric hypercar with insane acceleration.",
                            Engine = "Electric Tri-Motor",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Tesla",
                            Mileage = 4000,
                            Model = "Model S Plaid",
                            PricePerDay = 1600m,
                            PricePerHour = 130m,
                            PricePerWeek = 9500m,
                            Province = "North West",
                            Year = 2024
                        },
                        new
                        {
                            Id = -9,
                            AverageRating = 4.8m,
                            CarType = "Convertible",
                            Description = "Opulent grand tourer for open-top luxury.",
                            Engine = "W12",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Bentley",
                            Mileage = 6000,
                            Model = "Continental GT",
                            PricePerDay = 2800m,
                            PricePerHour = 220m,
                            PricePerWeek = 17000m,
                            Province = "Northern Cape",
                            Year = 2023
                        },
                        new
                        {
                            Id = -10,
                            AverageRating = 5.0m,
                            CarType = "Luxury",
                            Description = "Bespoke serenity on wheels.",
                            Engine = "V12 Twin-Turbo",
                            ImageUrls = "[]",
                            IsAvailable = true,
                            Make = "Rolls-Royce",
                            Mileage = 500,
                            Model = "Ghost",
                            PricePerDay = 5000m,
                            PricePerHour = 400m,
                            PricePerWeek = 30000m,
                            Province = "Limpopo",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FridayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MondayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneMain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaturdayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SundayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThursdayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuesdayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WednesdayHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Address = "123 Luxury Avenue, Sandton, Johannesburg, 2196",
                            City = "Sandton",
                            Country = "South Africa",
                            EmailInfo = "info@safariwheels.co.za",
                            EmailSupport = "support@safariwheels.co.za",
                            Facebook = "https://facebook.com/safariwheels",
                            FridayHours = "8:00 AM - 6:00 PM",
                            Instagram = "https://instagram.com/safariwheels",
                            LinkedIn = "https://linkedin.com/company/safariwheels",
                            MondayHours = "8:00 AM - 6:00 PM",
                            PhoneMain = "+27 65 599 5628",
                            PhoneSupport = "+27 65 599 5628",
                            PostalCode = "2196",
                            Province = "Gauteng",
                            SaturdayHours = "9:00 AM - 4:00 PM",
                            Street = "123 Luxury Avenue",
                            SundayHours = "10:00 AM - 2:00 PM",
                            ThursdayHours = "8:00 AM - 6:00 PM",
                            TuesdayHours = "8:00 AM - 6:00 PM",
                            Twitter = "https://twitter.com/safariwheels",
                            WednesdayHours = "8:00 AM - 6:00 PM"
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CitiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitiesList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("float(10)");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("float(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Province");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Address = "123 Luxury Avenue, Sandton, Johannesburg",
                            CitiesJson = "[\"Johannesburg\",\"Pretoria\",\"Sandton\",\"Centurion\"]",
                            CitiesList = "[\"Johannesburg\",\"Pretoria\",\"Sandton\",\"Centurion\"]",
                            Hours = "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 4:00 PM",
                            IsActive = true,
                            Latitude = -26.106999999999999,
                            Longitude = 28.056000000000001,
                            Phone = "+27 11 123 4567",
                            Province = "Gauteng"
                        },
                        new
                        {
                            Id = -2,
                            Address = "45 Vineyard Road, Cape Town City Centre",
                            CitiesJson = "[\"Cape Town\",\"Stellenbosch\",\"Paarl\",\"Somerset West\"]",
                            CitiesList = "[\"Cape Town\",\"Stellenbosch\",\"Paarl\",\"Somerset West\"]",
                            Hours = "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 4:00 PM",
                            IsActive = true,
                            Latitude = -33.924999999999997,
                            Longitude = 18.423999999999999,
                            Phone = "+27 21 456 7890",
                            Province = "Western Cape"
                        },
                        new
                        {
                            Id = -3,
                            Address = "78 Beach Road, Umhlanga Rocks, Durban",
                            CitiesJson = "[\"Durban\",\"Umhlanga\",\"Ballito\",\"Pietermaritzburg\"]",
                            CitiesList = "[\"Durban\",\"Umhlanga\",\"Ballito\",\"Pietermaritzburg\"]",
                            Hours = "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 4:00 PM",
                            IsActive = true,
                            Latitude = -29.716999999999999,
                            Longitude = 31.065999999999999,
                            Phone = "+27 31 234 5678",
                            Province = "KwaZulu-Natal"
                        },
                        new
                        {
                            Id = -4,
                            Address = "32 Harbour View, Port Elizabeth Central",
                            CitiesJson = "[\"Port Elizabeth\",\"East London\",\"Grahamstown\"]",
                            CitiesList = "[\"Port Elizabeth\",\"East London\",\"Grahamstown\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
                            IsActive = true,
                            Latitude = -33.960000000000001,
                            Longitude = 25.602,
                            Phone = "+27 41 345 6789",
                            Province = "Eastern Cape"
                        },
                        new
                        {
                            Id = -5,
                            Address = "15 Park Road, Bloemfontein Central",
                            CitiesJson = "[\"Bloemfontein\",\"Welkom\",\"Bethlehem\"]",
                            CitiesList = "[\"Bloemfontein\",\"Welkom\",\"Bethlehem\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
                            IsActive = true,
                            Latitude = -29.116,
                            Longitude = 26.215,
                            Phone = "+27 51 456 7890",
                            Province = "Free State"
                        },
                        new
                        {
                            Id = -6,
                            Address = "9 Kruger Street, Nelspruit",
                            CitiesJson = "[\"Nelspruit\",\"Witbank\",\"Middleburg\"]",
                            CitiesList = "[\"Nelspruit\",\"Witbank\",\"Middleburg\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
                            IsActive = true,
                            Latitude = -25.475000000000001,
                            Longitude = 30.969999999999999,
                            Phone = "+27 13 567 8901",
                            Province = "Mpumalanga"
                        },
                        new
                        {
                            Id = -7,
                            Address = "27 Savannah Street, Polokwane Central",
                            CitiesJson = "[\"Polokwane\",\"Tzaneen\",\"Modimolle\"]",
                            CitiesList = "[\"Polokwane\",\"Tzaneen\",\"Modimolle\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
                            IsActive = true,
                            Latitude = -23.899999999999999,
                            Longitude = 29.449999999999999,
                            Phone = "+27 15 678 9012",
                            Province = "Limpopo"
                        },
                        new
                        {
                            Id = -8,
                            Address = "34 Platinum Road, Rustenburg",
                            CitiesJson = "[\"Rustenburg\",\"Mahikeng\",\"Potchefstroom\"]",
                            CitiesList = "[\"Rustenburg\",\"Mahikeng\",\"Potchefstroom\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 1:00 PM",
                            IsActive = true,
                            Latitude = -25.649999999999999,
                            Longitude = 27.239999999999998,
                            Phone = "+27 14 789 0123",
                            Province = "North West"
                        },
                        new
                        {
                            Id = -9,
                            Address = "12 Diamond Avenue, Kimberley",
                            CitiesJson = "[\"Kimberley\",\"Upington\",\"Springbok\"]",
                            CitiesList = "[\"Kimberley\",\"Upington\",\"Springbok\"]",
                            Hours = "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 9:00 AM - 12:00 PM",
                            IsActive = true,
                            Latitude = -28.741,
                            Longitude = 24.762,
                            Phone = "+27 53 890 1234",
                            Province = "Northern Cape"
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SafariWheels.API.Models.MessageReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("RepliedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageReplies");
                });

            modelBuilder.Entity("SafariWheels.API.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SafariWheels.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Address = "123 Luxury Avenue, Sandton",
                            CreatedAt = new DateTime(2026, 2, 22, 14, 10, 51, 451, DateTimeKind.Utc).AddTicks(4410),
                            DriverLicenseNumber = "ADMIN123",
                            Email = "admin@safariwheels.co.za",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "YWRtaW4xMjNzYWx0",
                            PhoneNumber = "+27 11 123 4567",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SafariWheels.API.Models.MessageReply", b =>
                {
                    b.HasOne("SafariWheels.API.Models.Message", "Message")
                        .WithMany("Replies")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SafariWheels.API.Models.Rental", b =>
                {
                    b.HasOne("SafariWheels.API.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafariWheels.API.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafariWheels.API.Models.Car", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SafariWheels.API.Models.Message", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SafariWheels.API.Models.User", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
